CREATE TABLE Employee_Data (
Employee_ID int primary key,
Age int,
Gender varchar(10),
Marital_Status varchar(10),
Department varchar(15),
Job_Role int,
Job_Level int,
Monthly_Income int,
Hourly_Rate int,
Years_at_Company int,
Years_in_Current_Role int,
Years_Since_Last_Promotion int,
Work_Life_Balance int,
Job_Satisfaction int,
Performance_Rating int,
Training_Hours_Last_Year int,
Overtime int,
Project_Count int,
Average_Hours_Worked_Per_Week int,
Absenteeism int,
Work_Environment_Satisfaction int,
Relationship_with_Manager int,
Job_Involvement	int,
Distance_From_Home int,
Number_of_Companies_Worked int,
Attrition varchar(15)
);